version: "3.7"
services:
  db:
    image: postgres:alpine3.19
    restart: always
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "${STAGE_PORT}:5432"
    volumes:
      - db_stage:/var/lib/postgresql/data
  cache:
    image: redis
    container_name: my-cache-stage
    ports:
      - "${REDIS_PORT}:6379"
volumes:
  db_stage:
    driver: local
