version: "3.7"
services:
  server:
    container_name: server
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${LOCAL_PORT}:5000"
    expose:
      - "${LOCAL_PORT}"
    volumes:
      - .:/app
    depends_on:
      - db
  db:
    image: postgres:alpine3.19
    restart: always
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - '${DEV_PORT}:5432'
    volumes:
      - db:/var/lib/postgresql/data
  db_test:
    image: postgres:alpine3.19
    restart: always
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - '${TEST_PORT}:5432'
  cache:
    image: redis
    container_name: my-cache
    ports:
      - "${REDIS_PORT}:6379"
volumes:
  db:
    driver: local
