name: Deploy to EC2 instance

on: workflow_dispatch

jobs:
  pull-and-deploy:
    runs-on: ubuntu-latest

    if: github.ref == 'refs/heads/main' # enable deploy only from main branch

    steps:

      - name: Deploy application via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /home/ubuntu/tmr
            git pull
            source venv/bin/activate
            pip install -r requirements.txt
            alembic --name prod upgrade head
            sudo systemctl restart tmr-flask-app