name: Deploy to AWS

on: workflow_dispatch

env:
  AWS_REGION: us-west-1
  ECR_REPOSITORY: tmr-flask-app
  BUILD_IMAGE: tmr-flask-app

permissions:
  id-token: write # This is required for requesting the JWT

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    if: github.ref == 'refs/heads/main' # enable deploy only from main branch

    steps:

      - name: Deploy application via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /home/ubuntu/tmr
            git pull
            source venv/bin/activate
            pip install -r requirements.txt
            alembic --name prod upgrade head
            sudo systemctl restart tmr-flask-app